# Netlify Configuration for FHE Guessing Game

[build]
  # Build command
  command = "cd frontend && npm install && npm run build"
  
  # Directory with the final build output
  publish = "frontend/dist"
  
  # Node version
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and CORS
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (will be set in Netlify UI or via CLI)
# VITE_FHE_CONTRACT_ADDRESS
# VITE_PLAINTEXT_CONTRACT_ADDRESS
# VITE_NETWORK_ID

